% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Dec-2019 15:27:52
%  MATLAB version: 9.6.0.1214997 (R2019a) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('a.mat');

A = saveVarsMat.A; % <724090x1 double> too many elements

BTB = saveVarsMat.BTB; % <1024x12 double> too many elements

BTB_Display = saveVarsMat.BTB_Display; % <719x12 double> too many elements

BTB_index = 719;

BTB_length = 1024;

BTB_ptr = 200;

Branch_Counter = 0;

Branch_Miss_Counter = 5833;

Branch_Wrong_Address_Counter = 3576;

Collisions = 5114;

Collisions_PC = saveVarsMat.Collisions_PC; % <1x5114 double> too many elements

Collisions_ptr = saveVarsMat.Collisions_ptr; % <1x5114 double> too many elements

Collisions_trace = saveVarsMat.Collisions_trace; % <1x5114 double> too many elements

Collissions_File = saveVarsMat.Collissions_File; % <5114x3 double> too many elements

Entry_Number = 724090;

Final_Predictor = saveVarsMat.Final_Predictor; % <1x1024 double> too many elements

Flag_PC_In_BTB = 0;

Flag_trace_Jump = 0;

GLOBAL = saveVarsMat.GLOBAL; % <1024x4 double> too many elements

GLOBAL_History = 11;

GLOBAL_History_Array = saveVarsMat.GLOBAL_History_Array; % <1x1024 double> too many elements

GLOBAL_History_column_Index = 4;

Global_Counter = 926;

Hit = 114845;

Local = saveVarsMat.Local; % <1x1024 double> too many elements

Local_Counter = 113919;

Miss = 5833;

PC = saveVarsMat.PC; % <1x1024 double> too many elements

Ptr = saveVarsMat.Ptr; % <1024x1 double> too many elements

Regular_Command_Counter = 599835;

Right_Prediction_Final_Total = 112047;

Right_Prediction_Final_Total2 = 112047;

Right_Prediction_GLOBAL = 112036;

Right_Prediction_GLOBAL2 = 112036;

Right_Prediction_Local = 111908;

Right_Prediction_Local2 = 111908;

Right_Prediction_array_GLOBAL = saveVarsMat.Right_Prediction_array_GLOBAL; % <1x1024 double> too many elements

Right_Prediction_array_Local = saveVarsMat.Right_Prediction_array_Local; % <1x1024 double> too many elements

Seltr = saveVarsMat.Seltr; % <1x1024 double> too many elements

Seltr_Dir = 11;

Seltr_Dir_Array = saveVarsMat.Seltr_Dir_Array; % <1x1024 double> too many elements

Taken = saveVarsMat.Taken; % <1x1024 double> too many elements

Target = saveVarsMat.Target; % <1x1024 double> too many elements

Wrong_Address = 3576;

Wrong_Address_Index = saveVarsMat.Wrong_Address_Index; % <1x3576 double> too many elements

Wrong_Prediction_Final_Total = 2798;

Wrong_Prediction_Final_Total2 = 2798;

Wrong_Prediction_GLOBAL = 2809;

Wrong_Prediction_GLOBAL2 = 2809;

Wrong_Prediction_Local = 2937;

Wrong_Prediction_Local2 = 2937;

Wrong_Prediction_array_GLOBAL = saveVarsMat.Wrong_Prediction_array_GLOBAL; % <1x1024 double> too many elements

Wrong_Prediction_array_Local = saveVarsMat.Wrong_Prediction_array_Local; % <1x1024 double> too many elements

ans = ...
  [2937 2809 2798;
   2937 2809 2798];

fileID = 3;

file_Collission = 3;

i = 724089;

j = 1024;

k = 5115;

trace_dec = saveVarsMat.trace_dec; % <724090x1 double> too many elements

trace_length = 724090;

clear saveVarsMat;
