trace_dec(:)=A(:,1); %Values from the source file in decimal format.
trace_dec=trace_dec';
trace_length = length(trace_dec); %Total number of Trace.txt enries.
BTB_length = 1024 ;
PC(1:BTB_length)=0 ;
Target(1:BTB_length)=0 ; % Branch Traget address.
GLOBAL(1:BTB_length,1:4)= 11 ; %GLOBAL Prediction Variable with 4 columns for two bit history
GLOBAL_History = 11 ;           %% Setting the GLOBAL History value to 11 as strong taken branches (two previous ones)
GLOBAL_History_Array(1:BTB_length) = 11 ;
GLOBAL_History_column_Index = 1 ;
Local(1:BTB_length) = 00 ; % Local Branch Prediction Variable
Seltr(1:BTB_length) = 01 ;
Seltr_Dir = 01 ;
Seltr_Dir_Array(1:BTB_length) = 0 ;
Branch_Counter = 0 ;
Branch_Wrong_Address_Counter = 0 ;
Branch_Miss_Counter = 0 ;
Wrong_Address_Index = 0 ;
Taken(1:BTB_length) = 0 ;
Hit = 0 ;
Collisions = 0 ;
Collisions_PC = 0 ;
Collisions_trace = 0 ;
Collisions_ptr = 0 ;
k = 1 ;
j = 1 ;
BTB_ptr = 0 ;
Ptr = (0:1023)' ;
Final_Predictor(1:BTB_length) = 00 ;
Wrong_Prediction_Local = 0 ;
Wrong_Prediction_Local2 = 0 ;
Right_Prediction_Final_Total = 0 ;
Wrong_Prediction_Final_Total = 0 ;
Right_Prediction_Final_Total2 = 0 ;
Wrong_Prediction_Final_Total2 = 0 ;
Right_Prediction_Local = 0 ;
Right_Prediction_Local2 = 0 ;
Wrong_Prediction_GLOBAL = 0 ;
Right_Prediction_GLOBAL = 0 ;
Wrong_Prediction_GLOBAL2 = 0 ;
Right_Prediction_GLOBAL2 = 0 ;
Wrong_Prediction_array_GLOBAL(1:BTB_length) = 0 ;
Right_Prediction_array_GLOBAL(1:BTB_length) = 0 ;
Wrong_Prediction_array_Local(1:BTB_length) = 0 ;
Right_Prediction_array_Local(1:BTB_length) = 0 ;
Regular_Command_Counter = 0;

Local_Counter = 0 ; 
Global_Counter = 0 ;