% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Dec-2019 18:18:17
%  MATLAB version: 9.6.0.1214997 (R2019a) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('Li_int.mat');

A = saveVarsMat.A; % <716529x1 double> too many elements

BTB = saveVarsMat.BTB; % <1024x12 double> too many elements

BTB_Display = saveVarsMat.BTB_Display; % <602x12 double> too many elements

BTB_index = 602;

BTB_length = 1024;

BTB_ptr = 388;

Branch_Counter = 0;

Branch_Miss_Counter = 3137;

Branch_Wrong_Address_Counter = 9953;

Collisions = 2535;

Collisions_PC = saveVarsMat.Collisions_PC; % <1x2535 double> too many elements

Collisions_ptr = saveVarsMat.Collisions_ptr; % <1x2535 double> too many elements

Collisions_trace = saveVarsMat.Collisions_trace; % <1x2535 double> too many elements

Collissions_File = saveVarsMat.Collissions_File; % <2535x3 double> too many elements

Entry_Number = 716529;

Final_Predictor = saveVarsMat.Final_Predictor; % <1x1024 double> too many elements

Flag_PC_In_BTB = 0;

Flag_trace_Jump = 0;

GLOBAL = saveVarsMat.GLOBAL; % <1024x4 double> too many elements

GLOBAL_History = 11;

GLOBAL_History_Array = saveVarsMat.GLOBAL_History_Array; % <1x1024 double> too many elements

GLOBAL_History_column_Index = 4;

Global_Counter = 6797;

Hit = 119603;

Local = saveVarsMat.Local; % <1x1024 double> too many elements

Local_Counter = 112806;

Miss = 3137;

PC = saveVarsMat.PC; % <1x1024 double> too many elements

Ptr = saveVarsMat.Ptr; % <1024x1 double> too many elements

Regular_Command_Counter = 583835;

Right_Prediction_Final_Total = 109816;

Right_Prediction_Final_Total2 = 109816;

Right_Prediction_GLOBAL = 109801;

Right_Prediction_GLOBAL2 = 109801;

Right_Prediction_Local = 109076;

Right_Prediction_Local2 = 109076;

Right_Prediction_array_GLOBAL = saveVarsMat.Right_Prediction_array_GLOBAL; % <1x1024 double> too many elements

Right_Prediction_array_Local = saveVarsMat.Right_Prediction_array_Local; % <1x1024 double> too many elements

Seltr = saveVarsMat.Seltr; % <1x1024 double> too many elements

Seltr_Dir = 11;

Seltr_Dir_Array = saveVarsMat.Seltr_Dir_Array; % <1x1024 double> too many elements

Taken = saveVarsMat.Taken; % <1x1024 double> too many elements

Target = saveVarsMat.Target; % <1x1024 double> too many elements

Wrong_Address = 9953;

Wrong_Address_Index = saveVarsMat.Wrong_Address_Index; % <1x9953 double> too many elements

Wrong_Prediction_Final_Total = 9787;

Wrong_Prediction_Final_Total2 = 9787;

Wrong_Prediction_GLOBAL = 9802;

Wrong_Prediction_GLOBAL2 = 9802;

Wrong_Prediction_Local = 10527;

Wrong_Prediction_Local2 = 10527;

Wrong_Prediction_array_GLOBAL = saveVarsMat.Wrong_Prediction_array_GLOBAL; % <1x1024 double> too many elements

Wrong_Prediction_array_Local = saveVarsMat.Wrong_Prediction_array_Local; % <1x1024 double> too many elements

ans = ...
  [10527 9802 9787;
   10527 9802 9787];

fileID = 3;

file_Collission = 3;

i = 716528;

j = 1024;

k = 2536;

trace_dec = saveVarsMat.trace_dec; % <716529x1 double> too many elements

trace_length = 716529;

clear saveVarsMat;
