% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Dec-2019 19:25:46
%  MATLAB version: 9.6.0.1214997 (R2019a) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('Spice_FP_new_2.mat');

A = saveVarsMat.A; % <788262x1 double> too many elements

BTB = saveVarsMat.BTB; % <1024x12 double> too many elements

BTB_Display = saveVarsMat.BTB_Display; % <581x12 double> too many elements

BTB_index = 581;

BTB_length = 1024;

BTB_ptr = 548;

Branch_Counter = 0;

Branch_Miss_Counter = 6597;

Branch_Wrong_Address_Counter = 8221;

Collisions = 6016;

Collisions_PC = saveVarsMat.Collisions_PC; % <1x6016 double> too many elements

Collisions_ptr = saveVarsMat.Collisions_ptr; % <1x6016 double> too many elements

Collisions_trace = saveVarsMat.Collisions_trace; % <1x6016 double> too many elements

Collissions_File = saveVarsMat.Collissions_File; % <6016x3 double> too many elements

Entry_Number = 788262;

Final_Predictor = saveVarsMat.Final_Predictor; % <1x1024 double> too many elements

Flag_PC_In_BTB = 0;

Flag_trace_Jump = 0;

GLOBAL = saveVarsMat.GLOBAL; % <1024x4 double> too many elements

GLOBAL_History = 11;

GLOBAL_History_Array = saveVarsMat.GLOBAL_History_Array; % <1x1024 double> too many elements

GLOBAL_History_column_Index = 4;

Global_Counter = 18340;

Hit = 120284;

Local = saveVarsMat.Local; % <1x1024 double> too many elements

Local_Counter = 101944;

Miss = 6597;

PC = saveVarsMat.PC; % <1x1024 double> too many elements

Ptr = saveVarsMat.Ptr; % <1024x1 double> too many elements

Regular_Command_Counter = 653159;

Right_Prediction_Final_Total = 113533;

Right_Prediction_Final_Total2 = 113533;

Right_Prediction_GLOBAL = 113588;

Right_Prediction_GLOBAL2 = 113588;

Right_Prediction_Local = 111874;

Right_Prediction_Local2 = 111874;

Right_Prediction_array_GLOBAL = saveVarsMat.Right_Prediction_array_GLOBAL; % <1x1024 double> too many elements

Right_Prediction_array_Local = saveVarsMat.Right_Prediction_array_Local; % <1x1024 double> too many elements

Seltr = saveVarsMat.Seltr; % <1x1024 double> too many elements

Seltr_Dir = 11;

Seltr_Dir_Array = saveVarsMat.Seltr_Dir_Array; % <1x1024 double> too many elements

Taken = saveVarsMat.Taken; % <1x1024 double> too many elements

Target = saveVarsMat.Target; % <1x1024 double> too many elements

Wrong_Address = 8221;

Wrong_Address_Index = saveVarsMat.Wrong_Address_Index; % <1x8221 double> too many elements

Wrong_Prediction_Final_Total = 6751;

Wrong_Prediction_Final_Total2 = 6751;

Wrong_Prediction_GLOBAL = 14917;

Wrong_Prediction_GLOBAL2 = 6696;

Wrong_Prediction_Local = 16631;

Wrong_Prediction_Local2 = 8410;

Wrong_Prediction_array_GLOBAL = saveVarsMat.Wrong_Prediction_array_GLOBAL; % <1x1024 double> too many elements

Wrong_Prediction_array_Local = saveVarsMat.Wrong_Prediction_array_Local; % <1x1024 double> too many elements

ans = ...
  [8410 6696 6751;
   16631 14917 6751];

fileID = 3;

file_Collission = 3;

i = 788261;

j = 1024;

k = 6017;

trace_dec = saveVarsMat.trace_dec; % <788262x1 double> too many elements

trace_length = 788262;

clear saveVarsMat;
